### PR TITLE
Derive clone.

### PR DESCRIPTION
**Pull request by Wopple**
This derives clone for ergonomics in other code bases.

I also added a gitignore line to exclude intellij files.

### CODE REVIEW

**Comment by Sayan751** [comment]
@Wopple Thank you for the PR. Can you please add some tests as well for the `Clone` trait?

**Comment by Wopple** [comment]
I'm not sure how, I took a lot at the tests and they all seem generated.

**Comment by Sayan751** [comment]
@Wopple you can add your test file under the `rust-lib/tests` directory and it will be picked up.

**Comment by Wopple** [comment]
Okay.

**Pull request merged**
